version: '3.1'
services:
  elasticsearch:
    build:
      context: ./es
    container_name: es
    environment:
      - cluster.name=es-cluster
      - node.name=master
      # disabling xpack since we don't use it and it installed by default in this image
      # ES v6 contains -OSS alternatives that don't contain xpack
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false

      - network.host=0.0.0.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200

  cerebro:
    image: lmenezes/cerebro:0.8.1
    container_name: cerebro
    ports:
      - 9000:9000

  redis: 
    image: redis:5.0.1-alpine
    container_name: redis
    
    # running in privileged mode is for resolving the Redis warning: 
    # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel.
    privileged: true

    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redisdata:/data
    # entrypoint: redis-server --appendonly yes
    # alternative to entrypoint and including additional configuration commands:
    command: >
      sh -c " echo never > /sys/kernel/mm/transparent_hugepage/enabled &&
              sysctl -w net.core.somaxconn=1024 &&
              redis-server --appendonly yes"

  prizm:
    build:
      context: prizm/
      dockerfile: Dockerfile_v11
      # dockerfile: Dockerfile_v12
      # dockerfile: Dockerfile_v13
    image: prizm:11.2
    # image: prizm:12.4
    # image: prizm:13
    container_name: prizmdoc
    ports:
      - 18001:18001
      - 18681:18681
      - 18682:18682
    tty: true
    stdin_open: true
    secrets:
      - prizm_license
    container_name: prizm
    entrypoint: ["/usr/local/docker-entrypoint.sh"]

secrets:
  prizm_license: 
    # file: ./prizm/license_v11.txt
    # file: ./prizm/license_v12.txt
    file: ./prizm/license_v11.txt

volumes:
  esdata:
  redisdata:
  prizmlogs: