FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

COPY pdutil.sh /usr/local/

RUN apt-get update \
	&& echo exit 0 > /usr/sbin/policy-rc.d \
	&& apt-get install locales -y \
	&& locale-gen en_US.UTF-8 \
	&& apt-get install dialog apt-utils -y \
	&& apt-get install -y fontconfig \
	&& apt-get install -y rsyslog \
	&& apt-get install -y libcups2 \
	&& apt-get install -y libdbus-glib-1-2 \
	&& apt-get install -y libexif12 \
	&& apt-get install -y libjpeg62 \
	&& apt-get install -y libxinerama1 \
	&& apt-get install -y libxrender1 \
	&& apt-get install -y libxtst6 \
	&& apt-get install -y libxslt1.1 \
	&& apt-get install -y libglu1-mesa \
	&& apt-get install -y lsof \
	&& apt-get install -y libcairo2 \
	# && apt-get install -y libgif4 \ 
	# && apt-get install -y libopenjpeg2 \
	&& /usr/local/pdutil.sh install --version=12.4

ENV DEBIAN_FRONTEND teletype

COPY ./v12and13/docker-entrypoint.sh /usr/local