FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

COPY pdutil.sh /usr/local/

RUN apt-get update \
	&& echo exit 0 > /usr/sbin/policy-rc.d \
	&& apt-get install locales -y \
	&& locale-gen en_US.UTF-8 \
	&& apt-get install -y libdbus-glib-1-2 \
	&& apt-get install -y libexif12 \
	&& apt-get install -y libjpeg62 \
	&& apt-get install -y libxinerama1 \
	&& apt-get install -y libxtst6 \
	&& apt-get install -y libxslt1.1 \
	&& apt-get install -y libglu1-mesa \
	&& apt-get install -y lsof \
	&& apt-get install -y libgif4 \ 
	&& apt-get install -y libopenjpeg2 \
	&& apt-get install -y imagemagick \
	&& apt-get install -y xvfb \
	&& apt-get install -y x11-xkb-utils \
	&& apt-get install -y xfonts-base \
	&& apt-get install -y xfonts-scalable \
	&& apt-get install -y xfonts-unifont \
	&& apt-get install -y xserver-xorg-core \
	&& apt-get install -y xfonts-100dpi xfonts-75dpi xfonts-cyrillic \
	&& apt-get install -y libxi6 \
	&& /usr/local/pdutil.sh install --headless --version=11.2

ENV DEBIAN_FRONTEND teletype

COPY ./v11/docker-entrypoint.sh /usr/local