FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

COPY pdutil.sh /usr/local/

RUN apt-get update \
	&& apt-get install locales -y \
	&& locale-gen en_US.UTF-8 \
	&& apt-get install dialog apt-utils -y \
	&& apt-get install -y xvfb \
	&& apt-get install -y fontconfig \
	&& apt-get install -y libcups2 \
	&& apt-get install -y libdbus-glib-1-2 \
	&& apt-get install -y libexif12 \
	&& apt-get install -y libjpeg62 \
	&& apt-get install -y libxinerama1 \
	&& apt-get install -y libxrender1 \
	&& apt-get install -y libxtst6 \
	&& apt-get install -y libxslt1.1 \
	&& apt-get install -y libglu1-mesa \
	&& apt-get install -y lsof \
	&& apt-get install -y libcairo2 \
	&& /usr/local/pdutil.sh install --headless

ENV DEBIAN_FRONTEND teletype

ENTRYPOINT Xvfb :20 &> /dev/null & export DISPLAY=:20 \
	&& /usr/share/prizm/java/jre8/bin/java -jar /usr/share/prizm/plu/plu.jar deploy write "PrizmDoc" 2.0.EHK8bLrzIHX5bhKU93bHW39LIhI4IUR4b4XzWHGstAWsizb5E3EyGaGfn5WHELRsR5cabLnzIHWLIh9UiUiHK3XfXhWpXUb4WpXzIzrsIAb8tzK1n3ryiyihGfQzGAQUW1OyQLRHXHifEhO39sO5IUrfnhQyEUGatyO5X1EsRAE3W5nHK3tyI4WhX1QHKhbst1GaIfOHX5OhIh9UcUGHn3KLnhcpiUt4i4rHOzKsXAWsIzG1r3EycatLI1WTiLXsi59y9LczRHQfrAcUEUXHW39LbhcptUI4rpiHKHE3ifb8tHn1c3KaQyWLb1nHKfW8Q19aXhX5iAQfKAO4XUtHK39LRhKpQUO4rpiHKHXUifOUWHn1RUWatyXAcHO5r5GyWfQ8Q5bA9hI1Ih93OsQ5O8rfWAE4E3KaEaG1iAnyIHKaWHE5K39sc8QfX1chGLtsK5Oyb1cAQhW1cAnpIpXh93tLIhOpbUK4t3RzXzKsXzIsiz91EUiaXQ9Hs \
	&& /usr/share/prizm/scripts/pccis.sh start